name: downloader
description: App that allows fast downloads of files.
publish_to: 'none' 

version: 0.0.1+1

environment:
  sdk: '>=3.1.0 <4.0.0'

isar_version: &isar_version 3.1.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  path_provider: ^2.1.1
  go_router: ^11.0.0
  isar: *isar_version
  isar_flutter_libs: *isar_version
  mobx: ^2.2.0
  flutter_mobx: ^2.1.0
  file_picker: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  isar_generator: *isar_version
  build_runner: ^2.4.6
  mobx_codegen: ^2.4.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #



# For details regarding fonts from package dependencies,
# see https://flutter.dev/custom-fonts/#from-packages
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec